export enum OrderStatus {
	PENDING = 'PENDING',
	PROCESSING = 'PROCESSING',
	SHIPPED = 'SHIPPED',
	OUT_FOR_DELIVERY = 'out_for_delivery',
	DELIVERED = 'DELIVERED',
	COMPLETED = 'completed',
	CANCELLED = 'CANCELLED',
	REFUNDED = 'REFUNDED',
}
